# Generated by Django 5.1.4 on 2025-01-16 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slaves', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slave',
            name='durability',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='slave',
            name='race',
            field=models.CharField(default='black', max_length=100),
        ),
    ]
