# Generated by Django 5.1.4 on 2025-01-16 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slaves', '0002_slave_durability_slave_race'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slave',
            name='durability',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='slave',
            name='race',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
